name: Publish

on:
  push:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash .ci/runChecks.sh

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: sudo apt-get update && sudo apt-get install jq -y
      - run: npm ci
      - run: npm run build:ci
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: ["run-checks"]
